name: Build LaTeX document

on:
  push:
    branches:
      - main

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: Clean Auxiliary Files
        run: rm -f report/*.aux report/*.log report/*.toc report/*.lof report/*.lot report/*.out report/*.bbl report/*.bcf report/*.blg report/*.xml

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: report/report.tex
          work_in_root_file_dir: true

      - name: Debug File Locations
        run: ls -lR report

      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: report
          path: report/report.pdf
